version: "3.9"

services:
  api:
    build: .
    environment:
      INFOZONE_ROOT: /app                  # internal root used by your code
      OPENAI_API_KEY: ${OPENAI_API_KEY}    # from .env (do NOT commit .env)
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-5}
      OPENAI_REASONING_EFFORT: ${OPENAI_REASONING_EFFORT:-medium}
      RTLS_CODE_TIMEOUT_SEC: ${RTLS_CODE_TIMEOUT_SEC:-1800}
      TZ: ${TZ:-UTC}
    volumes:
      - ./uploads:/app/uploads
      - ./.runs:/app/.runs
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
